/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ness
 */
public class Vista extends javax.swing.JFrame {
    VRegistrarTrabajo RegistrarTrabajo = new VRegistrarTrabajo();
    VAumentarHoras aumentarHoras = new VAumentarHoras();

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mRegistrarTrabajo = new javax.swing.JMenuItem();
        mAumentarHoras = new javax.swing.JMenuItem();
        mAumentarValorMaterial = new javax.swing.JMenuItem();
        mFinalizarTrabajo = new javax.swing.JMenuItem();
        mMostrarTrabajo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SOFTWARE PARA GESTIONAR REPARACIONES Y REVISIONES");

        jLabel2.setText("REALIZADO POR:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NESTOR VILLAFAÑE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CARLOS MACEA");

        jMenu1.setText("TRABAJOS");

        mRegistrarTrabajo.setText("REGISTRAR TRABAJO");
        mRegistrarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarTrabajoActionPerformed(evt);
            }
        });
        jMenu1.add(mRegistrarTrabajo);

        mAumentarHoras.setText("AUMENTAR HORAS");
        mAumentarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAumentarHorasActionPerformed(evt);
            }
        });
        jMenu1.add(mAumentarHoras);

        mAumentarValorMaterial.setText("AUMENTAR VALOR MATERIALES");
        mAumentarValorMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAumentarValorMaterialActionPerformed(evt);
            }
        });
        jMenu1.add(mAumentarValorMaterial);

        mFinalizarTrabajo.setText("FINALIZAR TRABAJO");
        mFinalizarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFinalizarTrabajoActionPerformed(evt);
            }
        });
        jMenu1.add(mFinalizarTrabajo);

        mMostrarTrabajo.setText("MOSTRAR TRABAJO");
        jMenu1.add(mMostrarTrabajo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mRegistrarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarTrabajoActionPerformed
        // TODO add your handling code here:
       //RegistrarTrabajo.setVisible(true);
    }//GEN-LAST:event_mRegistrarTrabajoActionPerformed

    private void mAumentarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAumentarHorasActionPerformed
        // TODO add your handling code here:
        //aumentarHoras.setVisible(true);
    }//GEN-LAST:event_mAumentarHorasActionPerformed

    private void mAumentarValorMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAumentarValorMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAumentarValorMaterialActionPerformed

    private void mFinalizarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFinalizarTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFinalizarTrabajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem mAumentarHoras;
    public javax.swing.JMenuItem mAumentarValorMaterial;
    public javax.swing.JMenuItem mFinalizarTrabajo;
    public javax.swing.JMenuItem mMostrarTrabajo;
    public javax.swing.JMenuItem mRegistrarTrabajo;
    // End of variables declaration//GEN-END:variables
}
